export const keysScaleRatio = 0.28;

export const keysDimension = {
  white: {
    width: 60,
    height: 200,
    borderWidth: 2,
    mini: {
      width: 60 * keysScaleRatio,
      height: 200 * keysScaleRatio,
      borderWidth: 1,
    }
  },
  black: {
    width: 38,
    height: 120,
    mini: {
      width: Math.ceil(38 * keysScaleRatio),
      height: 120 * keysScaleRatio,
    }
  }
} as const;

// from C1 to B7
export const keysAll: PianoKey[] = [
  // { note: 'A0', type: 'white', label: 'A' },
  // { note: 'A#0', type: 'black', label: 'A#' },
  // { note: 'B0', type: 'white', label: 'B' },
  { note: 'C1', type: 'white', label: 'C' },
  { note: 'C#1', type: 'black', label: 'C#' },
  { note: 'D1', type: 'white', label: 'D' },
  { note: 'D#1', type: 'black', label: 'D#' },
  { note: 'E1', type: 'white', label: 'E' },
  { note: 'F1', type: 'white', label: 'F' },
  { note: 'F#1', type: 'black', label: 'F#' },
  { note: 'G1', type: 'white', label: 'G' },
  { note: 'G#1', type: 'black', label: 'G#' },
  { note: 'A1', type: 'white', label: 'A' },
  { note: 'A#1', type: 'black', label: 'A#'},
  { note: 'B1', type: 'white', label: 'B' },
  { note: 'C2', type: 'white', label: 'C' },
  { note: 'C#2', type: 'black', label: 'C#' },
  { note: 'D2', type: 'white', label: 'D' },
  { note: 'D#2', type: 'black', label: 'D#' },
  { note: 'E2', type: 'white', label: 'E' },
  { note: 'F2', type: 'white', label: 'F' },
  { note: 'F#2', type: 'black', label: 'F#' },
  { note: 'G2', type: 'white', label: 'G' },
  { note: 'G#2', type: 'black', label: 'G#' },
  { note: 'A2', type: 'white', label: 'A' },
  { note: 'A#2', type: 'black', label: 'A#' },
  { note: 'B2', type: 'white', label: 'B' },
  { note: 'C3', type: 'white', label: 'C' },
  { note: 'C#3', type: 'black', label: 'C#' },
  { note: 'D3', type: 'white', label: 'D' },
  { note: 'D#3', type: 'black', label: 'D#' },
  { note: 'E3', type: 'white', label: 'E' },
  { note: 'F3', type: 'white', label: 'F' },
  { note: 'F#3', type: 'black', label: 'F#' },
  { note: 'G3', type: 'white', label: 'G' },
  { note: 'G#3', type: 'black', label: 'G#' },
  { note: 'A3', type: 'white', label: 'A' },
  { note: 'A#3', type: 'black', label: 'A#' },
  { note: 'B3', type: 'white', label: 'B' },
  { note: 'C4', type: 'white', label: 'C' },
  { note: 'C#4', type: 'black', label: 'C#' },
  { note: 'D4', type: 'white', label: 'D' },
  { note: 'D#4', type: 'black', label: 'D#' },
  { note: 'E4', type: 'white', label: 'E' },
  { note: 'F4', type: 'white', label: 'F' },
  { note: 'F#4', type: 'black', label: 'F#' },
  { note: 'G4', type: 'white', label: 'G' },
  { note: 'G#4', type: 'black', label: 'G#' },
  { note: 'A4', type: 'white', label: 'A' },
  { note: 'A#4', type: 'black', label: 'A#' },
  { note: 'B4', type: 'white', label: 'B' },
  { note: 'C5', type: 'white', label: 'C' },
  { note: 'C#5', type: 'black', label: 'C#' },
  { note: 'D5', type: 'white', label: 'D' },
  { note: 'D#5', type: 'black', label: 'D#' },
  { note: 'E5', type: 'white', label: 'E' },
  { note: 'F5', type: 'white', label: 'F' },
  { note: 'F#5', type: 'black', label: 'F#' },
  { note: 'G5', type: 'white', label: 'G' },
  { note: 'G#5', type: 'black', label: 'G#' },
  { note: 'A5', type: 'white', label: 'A' },
  { note: 'A#5', type: 'black', label: 'A#' },
  { note: 'B5', type: 'white', label: 'B' },
  { note: 'C6', type: 'white', label: 'C' },
  { note: 'C#6', type: 'black', label: 'C#' },
  { note: 'D6', type: 'white', label: 'D' },
  { note: 'D#6', type: 'black', label: 'D#' },
  { note: 'E6', type: 'white', label: 'E' },
  { note: 'F6', type: 'white', label: 'F' },
  { note: 'F#6', type: 'black', label: 'F#' },
  { note: 'G6', type: 'white', label: 'G' },
  { note: 'G#6', type: 'black', label: 'G#' },
  { note: 'A6', type: 'white', label: 'A' },
  { note: 'A#6', type: 'black', label: 'A#' },
  { note: 'B6', type: 'white', label: 'B' },
  { note: 'C7', type: 'white', label: 'C7' },
  { note: 'C#7', type: 'black', label: 'C#7' },
  { note: 'D7', type: 'white', label: 'D7' },
  { note: 'D#7', type: 'black', label: 'D#7' },
  { note: 'E7', type: 'white', label: 'E7' },
  { note: 'F7', type: 'white', label: 'F7' },
  { note: 'F#7', type: "black", label:"F#7" },
  { note: 'G7', type: 'white', label: 'G7' },
  { note: 'G#7', type: 'black', label: 'G#7' },
  { note: 'A7', type: 'white', label: 'A7' },
  { note: 'A#7', type: 'black', label: 'A#7' },
  { note: 'B7', type: 'white', label: 'B7' },
] satisfies PianoKey[];
