export const keysScaleRatio = 0.4;

export const keysDimension = {
  white: {
    width: 32,
    height: 160,
    borderWidth: 2,
    mini: {
      width: 32 * keysScaleRatio,
      height: 160 * keysScaleRatio,
      borderWidth: 1,
    }
  },
  black: {
    width: 18,
    height: 95,
    mini: {
      width: Math.ceil(18 * keysScaleRatio),
      height: 95 * keysScaleRatio,
    }
  }
} as const;

// from A0 to B7
export const keysAll: PianoKey[] = [
  // { note: 'A0', type: 'white', label: 'A' },
  // { note: 'A#0', type: 'black', label: 'A#' },
  // { note: 'B0', type: 'white', label: 'B' },
  { note: 'C1', type: 'white', label: 'C' },
  { note: 'C#1', type: 'black', label: 'C#' },
  { note: 'D1', type: 'white', label: 'D' },
  { note: 'D#1', type: 'black', label: 'D#' },
  { note: 'E1', type: 'white', label: 'E' },
  { note: 'F1', type: 'white', label: 'F' },
  { note: 'F#1', type: 'black', label: 'F#' },
  { note: 'G1', type: 'white', label: 'G' },
  { note: 'G#1', type: 'black', label: 'G#' },
  { note: 'A1', type: 'white', label: 'A' },
  { note: 'A#1', type: 'black', label: 'A#'},
  { note: 'B1', type: 'white', label: 'B' },
  { note: 'C2', type: 'white', label: 'C' },
  { note: 'C#2', type: 'black', label: 'C#' },
  { note: 'D2', type: 'white', label: 'D' },
  { note: 'D#2', type: 'black', label: 'D#' },
  { note: 'E2', type: 'white', label: 'E' },
  { note: 'F2', type: 'white', label: 'F' },
  { note: 'F#2', type: 'black', label: 'F#' },
  { note: 'G2', type: 'white', label: 'G' },
  { note: 'G#2', type: 'black', label: 'G#' },
  { note: 'A2', type: 'white', label: 'A' },
  { note: 'A#2', type: 'black', label: 'A#' },
  { note: 'B2', type: 'white', label: 'B' },
  { note: 'C3', type: 'white', label: 'C' },
  { note: 'C#3', type: 'black', label: 'C#' },
  { note: 'D3', type: 'white', label: 'D' },
  { note: 'D#3', type: 'black', label: 'D#' },
  { note: 'E3', type: 'white', label: 'E' },
  { note: 'F3', type: 'white', label: 'F' },
  { note: 'F#3', type: 'black', label: 'F#' },
  { note: 'G3', type: 'white', label: 'G' },
  { note: 'G#3', type: 'black', label: 'G#' },
  { note: 'A3', type: 'white', label: 'A' },
  { note: 'A#3', type: 'black', label: 'A#' },
  { note: 'B3', type: 'white', label: 'B' },
  { note: 'C4', type: 'white', label: 'C' },
  { note: 'C#4', type: 'black', label: 'C#' },
  { note: 'D4', type: 'white', label: 'D' },
  { note: 'D#4', type: 'black', label: 'D#' },
  { note: 'E4', type: 'white', label: 'E' },
  { note: 'F4', type: 'white', label: 'F' },
  { note: 'F#4', type: 'black', label: 'F#' },
  { note: 'G4', type: 'white', label: 'G' },
  { note: 'G#4', type: 'black', label: 'G#' },
  { note: 'A4', type: 'white', label: 'A' },
  { note: 'A#4', type: 'black', label: 'A#' },
  { note: 'B4', type: 'white', label: 'B' },
  { note: 'C5', type: 'white', label: 'C' },
  { note: 'C#5', type: 'black', label: 'C#' },
  { note: 'D5', type: 'white', label: 'D' },
  { note: 'D#5', type: 'black', label: 'D#' },
  { note: 'E5', type: 'white', label: 'E' },
  { note: 'F5', type: 'white', label: 'F' },
  { note: 'F#5', type: 'black', label: 'F#' },
  { note: 'G5', type: 'white', label: 'G' },
  { note: 'G#5', type: 'black', label: 'G#' },
  { note: 'A5', type: 'white', label: 'A' },
  { note: 'A#5', type: 'black', label: 'A#' },
  { note: 'B5', type: 'white', label: 'B' },
  { note: 'C6', type: 'white', label: 'C' },
  { note: 'C#6', type: 'black', label: 'C#' },
  { note: 'D6', type: 'white', label: 'D' },
  { note: 'D#6', type: 'black', label: 'D#' },
  { note: 'E6', type: 'white', label: 'E' },
  { note: 'F6', type: 'white', label: 'F' },
  { note: 'F#6', type: 'black', label: 'F#' },
  { note: 'G6', type: 'white', label: 'G' },
  { note: 'G#6', type: 'black', label: 'G#' },
  { note: 'A6', type: 'white', label: 'A' },
  { note: 'A#6', type: 'black', label: 'A#' },
  { note: 'B6', type: 'white', label: 'B' },
  { note: 'C7', type: 'white', label: 'C' },
  { note: 'C#7', type: 'black', label: 'C#' },
  { note: 'D7', type: 'white', label: 'D' },
  { note: 'D#7', type: 'black', label: 'D#' },
  { note: 'E7', type: 'white', label: 'E' },
  { note: 'F7', type: 'white', label: 'F' },
  { note: 'F#7', type: 'black', label: 'F#' },
  { note: 'G7', type: 'white', label: 'G' },
  { note: 'G#7', type: 'black', label: 'G#' },
  { note: 'A7', type: 'white', label: 'A' },
  { note: 'A#7', type: 'black', label: 'A#' },
  { note: 'B7', type: 'white', label: 'B' },
] satisfies PianoKey[];

export const PIANO_AUDIO_SOURCES: Record<string, string> = {
  'A0': 'A0.mp3',
  'A#0': 'As0.mp3',
  'B0': 'B0.mp3',
  'C1': 'C1.mp3',
  'C#1': 'Cs1.mp3',
  'D1': 'D1.mp3',
  'D#1': 'Ds1.mp3',
  'E1': 'E1.mp3',
  'F1': 'F1.mp3',
  'F#1': 'Fs1.mp3',
  'G1': 'G1.mp3',
  'G#1': 'Gs1.mp3',
  'A1': 'A1.mp3',
  'A#1': 'As1.mp3',
  'B1': 'B1.mp3',
  'C2': 'C2.mp3',
  'C#2': 'Cs2.mp3',
  'D2': 'D2.mp3',
  'D#2': 'Ds2.mp3',
  'E2': 'E2.mp3',
  'F2': 'F2.mp3',
  'F#2': 'Fs2.mp3',
  'G2': 'G2.mp3',
  'G#2': 'Gs2.mp3',
  'A2': 'A2.mp3',
  'A#2': 'As2.mp3',
  'B2': 'B2.mp3',
  'C3': 'C3.mp3',
  'C#3': 'Cs3.mp3',
  'D3': 'D3.mp3',
  'D#3': 'Ds3.mp3',
  'E3': 'E3.mp3',
  'F3': 'F3.mp3',
  'F#3': 'Fs3.mp3',
  'G3': 'G3.mp3',
  'G#3': 'Gs3.mp3',
  'A3': 'A3.mp3',
  'A#3': 'As3.mp3',
  'B3': 'B3.mp3',
  'C4': 'C4.mp3',
  'C#4': 'Cs4.mp3',
  'D4': 'D4.mp3',
  'D#4': 'Ds4.mp3',
  'E4': 'E4.mp3',
  'F4': 'F4.mp3',
  'F#4': 'Fs4.mp3',
  'G4': 'G4.mp3',
  'G#4': 'Gs4.mp3',
  'A4': 'A4.mp3',
  'A#4': 'As4.mp3',
  'B4': 'B4.mp3',
  'C5': 'C5.mp3',
  'C#5': 'Cs5.mp3',
  'D5': 'D5.mp3',
  'D#5': 'Ds5.mp3',
  'E5': 'E5.mp3',
  'F5': 'F5.mp3',
  'F#5': 'Fs5.mp3',
  'G5': 'G5.mp3',
  'G#5': 'Gs5.mp3',
  'A5': 'A5.mp3',
  'A#5': 'As5.mp3',
  'B5': 'B5.mp3',
  'C6': 'C6.mp3',
  'C#6': 'Cs6.mp3',
  'D6': 'D6.mp3',
  'D#6': 'Ds6.mp3',
  'E6': 'E6.mp3',
  'F6': 'F6.mp3',
  'F#6': 'Fs6.mp3',
  'G6': 'G6.mp3',
  'G#6': 'Gs6.mp3',
  'A6': 'A6.mp3',
  'A#6': 'As6.mp3',
  'B6': 'B6.mp3',
  'C7': 'C7.mp3',
  'C#7': 'Cs7.mp3',
  'D7': 'D7.mp3',
  'D#7': 'Ds7.mp3',
  'E7': 'E7.mp3',
  'F7': 'F7.mp3',
  'F#7': 'Fs7.mp3',
  'G7': 'G7.mp3',
  'G#7': 'Gs7.mp3',
  'A7': 'A7.mp3',
  'A#7': 'As7.mp3',
  'B7': 'B7.mp3',
}
